# Generated by Django 5.0.6 on 2024-06-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='disponibilidad',
            field=models.JSONField(),
        ),
    ]
